sap.ui.require.preload({
	"sap/ui5/showcaseApp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","sap/ui5/showcaseApp/model/models"],function(e,t,i){"use strict";return e.extend("sap.ui5.showcaseApp.Component",{metadata:{events:{statusChanged:{}},manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.setModel(i.createDeviceModel(),"device");this.getRouter().initialize()}})});
},
	"sap/ui5/showcaseApp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e){"use strict";return e.extend("sap.ui5.showcaseApp.controller.App",{_iCarouselTimeout:0,_iCarouselLoopTime:1e5,onShowCaseComponentCreated:function(e){var o=e.getParameter("component");o.attachButtonClicked(this.onShowCaseButtonClicked,this)},onShowCaseButtonClicked:function(e){this.getOwnerComponent().getRouter().navTo("overview",{query:{project:e.getParameter("navTarget")}})}})});
},
	"sap/ui5/showcaseApp/controller/Contribute.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("sap.ui5.showcaseApp.controller.Contribute",{onOverview:function(){this.getOwnerComponent().getRouter().navTo("overview",{Project:"0"},true)}})});
},
	"sap/ui5/showcaseApp/controller/Overview.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/Filter","sap/ui/model/FilterOperator","sap/ui/core/UIComponent"],function(e,t,n,o){"use strict";return e.extend("sap.ui5.showcaseApp.controller.Overview",{_iCarouselTimeout:0,_iCarouselLoopTime:1e5,onInit:function(){this.getRouter().getRoute("overview").attachPatternMatched(this._onPatternMatched,this)},getRouter:function(){return o.getRouterFor(this)},onShowCaseComponentCreated:function(e){var t=e.getParameter("component");t.attachNavigateToPresentation(this.onNavigateToPresentation,this);t.attachNavigateToContributionPage(this.onNavigateToContributionPage,this)},onNavigateToPresentation:function(e){var t=this.getOwnerComponent().byId("app").getDomRef();if(t.requestFullscreen){t.requestFullscreen()}else if(t.mozRequestFullScreen){t.mozRequestFullScreen()}else if(t.webkitRequestFullscreen){t.webkitRequestFullscreen()}else if(t.msRequestFullscreen){t.msRequestFullscreen()}this.getRouter().navTo("presentation",{query:{project:e.getParameter("navTarget"),show:this._bExternal?"public":"all"}})},onNavigateToContributionPage:function(){this.getRouter().navTo("contribute")},_onPatternMatched:function(e){var o=e.getParameter("arguments")["?query"],i=o&&o.project||0,r=o&&o.show==="public",a="/"+i;this._bExternal=r;var s=this.byId("showCasePageComponent");if(!this._oComponentCreatedPromise){this._oComponentCreatedPromise=new Promise(function(e){s.attachComponentCreated(e)})}this._oComponentCreatedPromise.then(function(){var e=this.getComponentInstance().getRootControl();e.loaded().then(function(e){var o=e.byId("objectPageLayout");if(r){var i=o.getBinding("sections");var s=new t("classification",n.EQ,"public");i.filter(s)}function u(e){var t=this.getSections().filter(function(e){var t=10;return e.getBindingContext().getPath().substr(t)===a});setTimeout(function(){this.scrollToSection(t[0].getId())}.bind(this),typeof e==="boolean"?0:1e3)}if(!o.$().length){o.addEventDelegate({onAfterRendering:u.bind(o)})}else{u.bind(o)(true)}})}.bind(s))}})});
},
	"sap/ui5/showcaseApp/controller/Presentation.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent"],function(t,e){"use strict";return t.extend("sap.ui5.showcaseApp.controller.Presentation",{onInit:function(){var t=e.getRouterFor(this);var n=this.byId("presentationComponent");if(!this._oComponentCreatedPromise){this._oComponentCreatedPromise=new Promise(function(t){n.attachComponentCreated(t)})}t.getRoute("presentation").attachPatternMatched(this._onPatternMatched,this)},_onPatternMatched:function(t){var e=t.getParameter("arguments")["?query"],n=e&&e.project||0,o=e&&e.show==="public";this._bExternal=o;this._oComponentCreatedPromise.then(function(){var t=this.byId("presentationComponent").getComponentInstance().getRootControl();t.loaded().then(function(){t.getController().onRouteMatched(n,o)}.bind(t))}.bind(this))},onShowCaseComponentCreated:function(t){var e=t.getParameter("component");e.attachNavigateToPresentation(this.onNavigateToPresentation,this);e.attachNavigateToOverview(this.onNavigateToOverview,this)},onNavigateToOverview:function(t){this.getOwnerComponent().getRouter().navTo("overview",{query:{project:t.getParameter("navTarget"),show:this._bExternal?"public":"all"}})},onNavigateToPresentation:function(t){this.getOwnerComponent().getRouter().navTo("presentation",{query:{project:t.getParameter("navTarget"),show:this._bExternal?"public":"all"}},true)}})});
},
	"sap/ui5/showcaseApp/i18n/i18n.properties":'title=UI5 Showcases\nappTitle=UI5 Showcases\nappDescription=See UI5 in action!\ncontributeTitle=Contribute a Showcase',
	"sap/ui5/showcaseApp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"sap.ui5.showcaseApp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"sap.ui5.showcaseApp.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{},"sap.uxap":{},"showcaseslib":{}},"components":{"showcaseslib.showcase":{},"showcaseslib.showcasePage":{},"showcaseslib.contributionPage":{},"showcaseslib.presentation":{}}},"componentUsages":{"showcase":{"name":"showcaseslib.showcase"},"showcasePage":{"name":"showcaseslib.showcasePage"},"contributionPage":{"name":"showcaseslib.contributionPage"},"presentation":{"name":"showcaseslib.presentation"}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sap.ui5.showcaseApp.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"sap.ui5.showcaseApp.view","controlId":"app","controlAggregation":"pages","async":true,"bypassed":{"target":"overview"}},"routes":[{"pattern":"overview/:?query:","name":"overview","target":"overview"},{"pattern":"home","name":"home","target":"home"},{"pattern":"contribute","name":"contribute","target":"contribute"},{"pattern":"presentation/:?query:","name":"presentation","target":"presentation"}],"targets":{"overview":{"viewName":"Overview","viewId":"overview","viewLevel":0,"transition":"fade"},"home":{"viewName":"Home","viewId":"home","viewLevel":0},"contribute":{"viewName":"Contribute","viewId":"contribute","viewLevel":0},"presentation":{"viewName":"Presentation","viewId":"presentation","viewLevel":0,"transition":"fade"}}}}}',
	"sap/ui5/showcaseApp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"sap/ui5/showcaseApp/view/App.view.xml":'<mvc:View\n\tcontrollerName="sap.ui5.showcaseApp.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" class="sc-app"/></mvc:View>',
	"sap/ui5/showcaseApp/view/Contribute.view.xml":'<mvc:View\n\tid="contributeView"\n\tcontrollerName="sap.ui5.showcaseApp.controller.Contribute"\n\tdisplayBlock="true"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"\n\txmlns="sap.m"><Page\n\t\tid="page"\n\t\tshowHeader="true"\n\t\ttitle="{i18n>contributeTitle}"\n\t\tclass="sapUiContentPadding"\n\t\tshowNavButton="true"\n\t\tnavButtonPress=".onOverview"><core:ComponentContainer height="100%"\n\t\t\t\tid="showCasePageComponent"\n\t\t\t\tusage="contributionPage"/></Page></mvc:View>',
	"sap/ui5/showcaseApp/view/Home.view.xml":'<mvc:View\n\tcontrollerName="sap.ui5.showcaseApp.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"><Page id="page" showHeader="false"><core:ComponentContainer\n\t\t\tid="showCaseComponent"\n\t\t\tusage="showcase"\n\t\t\tcomponentCreated=".onShowCaseComponentCreated"/></Page></mvc:View>',
	"sap/ui5/showcaseApp/view/Overview.view.xml":'<mvc:View\n\tcontrollerName="sap.ui5.showcaseApp.controller.Overview"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"><Page id="page" showHeader="false"><core:ComponentContainer\n\t\t\tid="showCasePageComponent"\n\t\t\tusage="showcasePage"\n\t\t\tcomponentCreated=".onShowCaseComponentCreated"/></Page></mvc:View>\n',
	"sap/ui5/showcaseApp/view/Presentation.view.xml":'<mvc:View\n\tcontrollerName="sap.ui5.showcaseApp.controller.Presentation"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"><Page id="page" showHeader="false"><core:ComponentContainer\n\t\t\tid="presentationComponent"\n\t\t\tusage="presentation"\n\t\t\tcomponentCreated=".onShowCaseComponentCreated"/></Page></mvc:View>\n'
});
